################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= globalPb
# Cuda source files (compiled with cudacc)
CUFILES   := globalPb.cu  gpbmain.cu
# CU_DEPS         := globalPb.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 
LINKCCFILES := 
LINKCUFILES := 


################################################################################
# Rules and targets

SMVERSIONFLAGS := -arch sm_35
include ../common.mk
