################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= nonmax
# Cuda source files (compiled with cudacc)
CUFILES   := nonmaxmain.cu nonmax.cu 
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= 
LINKCCFILES := 
LINKCUFILES := 


################################################################################
# Rules and targets

SMVERSIONFLAGS := -arch sm_10
include ../common.mk
