################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= texton
# CUDA source files (compiled with cudacc)
CUFILES		:= textonFilter.cu texton.cu kmeans.cu
#CUFILES		:= textonFilter.cu texton.cu kmeans_noatomics.cu

CCFILES := filters.cpp

################################################################################
# Rules and targets

include ../common.mk

